### ISSUE TITLE
Double spaces in printed representation of SECRET-VALUE

### ISSUE THREAD

**Issue by phoe** [rotatef/secret-values#2]
The secret value objects are printed with double spaces inside them, like `#<SECRET-VALUES:SECRET-VALUE  {10043ABB23}>`. This is because the empty string is `princ`ed inside `print-unreadable-object` which causes the implementation to print double spaces around it.

Fixable by only printing to the stream if `secret-value-name` is not an empty string.

**Comment by bakketun** [comment]
Fixed.
